### ISSUE TITLE
Different steps/revolution for each motor

### ISSUE THREAD

**Issue by dlhenke** [MathieuDeprez/SmoothStepper-ESP32#1]
Is it possible to have different steps/revolution for each motor ?

I give an eye to source library and could not found.

**Comment by MathieuDeprez** [comment]
Hi @dlhenke 

If you want, you can create as many "SmoothStepper" Objects as you want. They represente a single motor.


```
const int stepsPerRevolution_1 = 2048;
const int stepsPerRevolution_2 = 4096;

SmoothStepper smoothStepper_1(stepsPerRevolution_1, 23, 22, 21, 19);
SmoothStepper smoothStepper_2(stepsPerRevolution_2, 16, 17, 18, 15);
```
